image: crops/yocto:ubuntu-18.04-base

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

.bitbake_simple: &bitbake_simple_template
  image: crops/yocto:ubuntu-18.04-base
  stage: build
  before_script:
    - ./scripts/setup.sh
  script:
    - ci/r0-simple.sh
  artifacts:
    paths:
      - build/tmp/deploy/
  cache:
    key: "gitlab_build"
    paths:
      - "build/tmp/cache/"
      - "build/tmp/downloads/"
      - "build/tmp/sstate-cache/"

simple-r0:
  extends: .bitbake_simple
  script:
    - ci/r0-simple.sh

simple-r1:
  extends: .bitbake_simple
  script:
    - ci/r1-simple.sh

simple-r0-layerindex-fetch:
  extends: .bitbake_simple
  script:
    - ci/r0-layerindex-fetch.sh

.kas_simple: &kas_simple_template
  image: kasproject/kas:2.1.1
  stage: build
  script:
    - kas build 'kas/r1-bb-examples.yml'
  variables:
    KAS_REPO_REF_DIR: "${CI_PROJECT_DIR}/build/tmp/downloads/"
  cache:
    key: "kas_simple"
    paths:
      - "build/tmp/cache/"
      - "build/tmp/downloads/"
      - "build/tmp/sstate-cache/"

r1-bb-examples:
  extends: .kas_simple
  script:
    - kas build 'kas/r1-bb-examples.yml'
