image: crops/yocto:ubuntu-18.04-base

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"' # Control when both branch pipelines and tag pipelines run.
      when: never
    # - if: $CI_COMMIT_TAG
    #   when: never
    # - if: $CI_COMMIT_BRANCH
    #   when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
      when: always
    # Default to never running.
    - when: never

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

.bitbake_simple: &bitbake_simple_template
  image: crops/yocto:ubuntu-18.04-base
  stage: build
  before_script:
    - ./scripts/setup.sh
  script:
    - ci/r0-simple.sh
  cache:
    key: "gitlab_build"
    paths:
      - "build/tmp/cache/" # PERSISTENT_DIR
      - "build/tmp/downloads/" # DL_DIR
      # - "build/tmp/sstate-cache/" # TODO: Not used yet.
  artifacts:
    paths:
      - build/tmp/deploy/ # DEPLOY_DIR
      - build/bitbake-cookerdaemon.log

simple-r0:
  extends: .bitbake_simple
  script:
    - ci/r0-simple.sh

simple-r1:
  extends: .bitbake_simple
  script:
    - ci/r1-simple.sh

.kas_simple: &kas_simple_template
  image: kasproject/kas:2.1.1
  stage: build
  script:
    - kas build 'kas/r1-bb-examples.yml'
  variables:
    # We will reuse the git repos created by the git fetcher for kas.
    KAS_REPO_REF_DIR: "${CI_PROJECT_DIR}/build/tmp/downloads/git/"
  cache:
    key: "kas_simple"
    paths:
      - "build/tmp/cache/" # PERSISTENT_DIR
      - "build/tmp/downloads/" # DL_DIR
      # - "build/tmp/sstate-cache/" # TODO: Not used yet.
  artifacts:
    paths:
      - build/tmp/deploy/ # DEPLOY_DIR
      - build/bitbake-cookerdaemon.log

r0-bb-examples:
  extends: .kas_simple
  script:
    - kas build 'kas/r0-base-only.yml'

r1-bb-examples:
  extends: .kas_simple
  script:
    - kas build 'kas/r1-bb-examples.yml'

r2-bitbake-examples:
  extends: .kas_simple
  script:
    - kas build 'kas/r2-bitbake-examples.yml'

r0-bb-base:
  extends: .kas_simple
  script:
    - kas build 'kas/r0-git-base-only.yml'

r1-git-bb-fetch:
  extends: .kas_simple
  script:
    - kas build 'kas/r1-git-bb-fetch.yml'

r1-git-bb-build-shell:
  extends: .kas_simple
  script:
    - kas build 'kas/r1-git-bb-build-shell.yml'
